const miles = 24;
const kilometers = 40;
const number = 1.609344;
const kilometersToMiles = kilometers / number;
const milesToKilometers = miles * number;
console.log("Distance conversions");
console.log("-----------------------");
console.log(kilometers + " kilometers are:");
console.log(kilometersToMiles + " miles");
console.log("----");
console.log(miles + " miles are:");
console.log(milesToKilometers + " kilometers");
console.log("\n");
